### PR TITLE
Revert "Temporarily revert removal of Python 3.5 support"

### PR DESCRIPTION
**Pull request by Kelketek**
## Description

This reverts the reversion of the Python 3.5 support.

## Test Instructions

Refer to the original PR: https://github.com/edx/blockstore/pull/91

This PR should be placed on stage (be it via merge to be confirmed later, or via this branch directly) and the configuration directive should be added:

```
AWS_S3_SIGNATURE_VERSION = 's3v4' 
```

...in the relevant .yml file for stage. If this works as expected, production should be similarly updated as this change is rolled out there.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [OSPR-5095](https://openedx.atlassian.net/browse/OSPR-5095) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by bradenmacdonald** [comment]
@Kelketek Can we set that env variable now, with the current version, then merge and deploy this, or will that cause problems?

**Comment by Kelketek** [comment]
@bradenmacdonald I believe that should work, yes. The setting is unlikely to cause problems with the old version. I could be wrong, but I don't see any reason why that wouldn't work.

**Review by kdmccormick — APPROVED** [review]
@bradenmacdonald Merge whenever you like. It should be on Stage  <30 minutes later.

**Comment by bradenmacdonald** [comment]
Thanks @kdmccormick. 

Reminder for you: to reduce risk, I have only made the configuration change on stage, so we'll need to also change `AWS_S3_SIGNATURE_VERSION` on prod before rolling this out all the way.

**Comment by edx-webhook** [comment]
@Kelketek 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/94&entry.1484655318=https://github.com/Kelketek&entry.752974735=2020-10-29+20:44&entry.1917517419=2020-11-02+17:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
