### PR TITLE
[SE-3451] Remove Python 3.5 support from docker/Makefile configuration.

### PR DESCRIPTION
**Pull request by Kelketek**
## Description

This removes support for Python 3.5 from the Makefile and Docker configuration files.

## Author Comments, Concerns, and Open Questions

I've not fully reversed the changes I made to the Makefile originally, but only removed all handling of 3.5 specifically. This should make it easier to upgrade again later by providing a template to build from without having to support 3.5.

This PR is dependent on https://github.com/edx/blockstore/pull/89, since that PR removes support from CI for 3.5.

## Test Instructions

1. Shut down the blockstore if it's currently running.
2. Run `make easyserver`
3. Run the unit tests per the README.
4. Run the integration tests, also per the README.
5. Blow away your cached images for blockstore and the cached volumes. If you're feeling frisky, do `make dev.up` in devstack to make sure your other devstack containers are in active use, make sure blockstore is stopped, and run `docker system prune` to blow away everything else. If you've got other containers you care about, don't do that. Instead, the following may be enough:

```
docker volume ls |grep blockstore|awk '{print $2}'|xargs docker volume rm
```

This command will probably error out, giving you a list of volumes that can't be destroyed because they're attached to containers. `docker kill`, then `docker rm` each container hash it mentions, then run the above command again.

6. Run steps 2-4 again.

## Reviewers
- [x] @bradenmacdonald 
- [ ] @kdmccormick

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [OSPR-5074](https://openedx.atlassian.net/browse/OSPR-5074) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Kelketek** [comment]
@kdmccormick I've recreated this pull request. Also noting for future readers that it has been approved by @bradenmacdonald [here](https://github.com/edx/blockstore/pull/90#pullrequestreview-513153871) and has been recreated due to an issue with the ticket generation.

**Review by kdmccormick — APPROVED** [review]
Cool. Thanks for re-opening this.

@Kelketek @bradenmacdonald any preferences on when I deploy this to production?

**Comment by edx-webhook** [comment]
@Kelketek 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/91&entry.1484655318=https://github.com/Kelketek&entry.752974735=2020-10-20+22:58&entry.1917517419=2020-10-21+15:38&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bradenmacdonald** [comment]
@kdmccormick Not particularly; whenever's good for you.

**Comment by kdmccormick** [comment]
@Kelketek `make easyserver` is now giving me:
```
Collecting inflect==4.1.0 (from -r requirements/local.txt (line 43))
  Could not find a version that satisfies the requirement inflect==4.1.0 (from -r requirements/local.txt (line 43)) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.1.0, 3.0.1, 3.0.2)
No matching distribution found for inflect==4.1.0 (from -r requirements/local.txt (line 43))
You are using pip version 9.0.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make: *** [Makefile:47: requirements] Error 1
make: *** [Makefile:27: dev.provision] Error 2
```
Reverting back two commits (aeb7265c13bf03d1d7787e6b8a69ae7c9dabd70e) fixes the issue for me.

**Comment by Kelketek** [comment]
@kdmccormick I can't seem to reproduce this. I blew away all docker cache and still couldn't. I was able to do a full build of the blockstore without issue.

**Comment by kdmccormick** [comment]
Hm, thanks for checking. I'll just wipe away my blockstore and start from a clean slate; hopefully that'll fix it.

**Comment by kdmccormick** [comment]
Fyi, we are holding off on production deployment. Stage Blockstore is throwing S3-related 500s, and I suspect it's related to the Django Storages 1.9->1.10 upgrade in this PR, which drops support for `boto`. I know Blockstore is ostensibly using `boto3`, but with our complicated config pipeline, it's possible something there is still using `boto`.

There's a thread in the edx/openecraft shared channel, but I'll update this PR when we confirm the issue.

**Pull request merged**
