### PR TITLE
[SE-3451] Remove Python 3.5 support from docker/Makefile configuration.

### PR DESCRIPTION
**Pull request by Kelketek**
## Description

This removes support for Python 3.5 from the Makefile and Docker configuration files.

## Author Comments, Concerns, and Open Questions

I've not fully reversed the changes I made to the Makefile originally, but only removed all handling of 3.5 specifically. This should make it easier to upgrade again later by providing a template to build from without having to support 3.5.

This PR is dependent on https://github.com/edx/blockstore/pull/89, since that PR removes support from CI for 3.5.

## Test Instructions

1. Shut down the blockstore if it's currently running.
2. Run `make easyserver`
3. Run the unit tests per the README.
4. Run the integration tests, also per the README.
5. Blow away your cached images for blockstore and the cached volumes. If you're feeling frisky, do `make dev.up` in devstack to make sure your other devstack containers are in active use, make sure blockstore is stopped, and run `docker system prune` to blow away everything else. If you've got other containers you care about, don't do that. Instead, the following may be enough:

```
docker volume ls |grep blockstore|awk '{print $2}'|xargs docker volume rm
```

This command will probably error out, giving you a list of volumes that can't be destroyed because they're attached to containers. `docker kill`, then `docker rm` each container hash it mentions, then run the above command again.

6. Run steps 2-4 again.

## Reviewers
- [ ] @bradenmacdonald 
- [ ] @kdmccormick

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [OSPR-5069](https://openedx.atlassian.net/browse/OSPR-5069) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by kdmccormick** [comment]
Thanks @Kelketek . This is a good PR, I don't think it's under the auspices of BD-14, although I might be mistaken.

**Comment by Kelketek** [comment]
@kdmccormick I misremembered the previous PR being under BD-14 for some reason. I can remove the tag if desired. @bradenmacdonald is there a BD or other tag this should be given in the title?

**Comment by kdmccormick** [comment]
That would be helpful; thanks!

**Comment by Kelketek** [comment]
@kdmccormick Done. Not sure if edx-webhook knows what to do converting FROM BD-14, though.

**Comment by kdmccormick** [comment]
I'm not sure it will either. Let's see what this does.

**Comment by kdmccormick** [comment]
I'll close it for a bit longer so that it marks the ticket as rejected.

**Comment by kdmccormick** [comment]
@Kelketek If you don't see a new OSPR ticket here within the next several minutes, I would just close this and open a new PR. Sorry for all the process nonsense.

**Review by bradenmacdonald — APPROVED** [review]
:+1:

- [x] I tested this: via integration tests
- [x] I read through the code
- [x] I checked for accessibility issues: n/a
- [x] Includes documentation: n/a

**Comment by natabene** [comment]
@Kelketek @kdmccormick I don't think bot can move from Blended back to OSPR. However, I can move tickets manually next time you need it.

**Comment by kdmccormick** [comment]
Thanks @natabene ; good to know!

**Pull request closed without merging**
