### PR TITLE
Fix #54: PATCHing a draft resets its links

### LINKED ISSUE #54: PATCHing a Draft's files deletes its links
Just quickly making a note about a bug I noticed... If I have a draft with a staged file and a new link, and then I PATCH a change to the staged file, the link in the draft disappears.

### PR DESCRIPTION
**Pull request by bradenmacdonald**
## Description

This is a fix for #54.

It also:
* Includes a ton of minor pylint fixes to get the build passing again with the current version of `edx-lint`
* Fixes the logging configuration to stop every request from being logged twice.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradenmacdonald! I've created [OSPR-4139](https://openedx.atlassian.net/browse/OSPR-4139) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@bradenmacdonald Thank you for your contribution. This is ready for our review?

**Comment by bradenmacdonald** [comment]
@natabene Yes, ready for review from @ormsbee :) I'll work with him on it.

Thanks!

**Comment by bradenmacdonald** [comment]
@ormsbee Squashed a bit; should be good to merge.

**Comment by edx-webhook** [comment]
@bradenmacdonald 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/64&entry.1484655318=https://github.com/bradenmacdonald&entry.752974735=2020-03-02+21:07&entry.1917517419=2020-04-16+20:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bradenmacdonald** [comment]
Thanks @ormsbee! We still have https://github.com/edx/blockstore/issues/61 "Race condition when adding files to a draft via PATCH" by the way, but I'm able to work around it for now. Still, at some point we need to fix it.

**Pull request merged**
