### PR TITLE
Update README to be more helpful

### PR DESCRIPTION
**Pull request by bradenmacdonald**
## Description

The README is missing a lot of useful information about how to use Blockstore today. This PR brings it up to date.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradenmacdonald! I've created [OSPR-4892](https://openedx.atlassian.net/browse/OSPR-4892) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the  [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by bradenmacdonald** [comment]
@arbrandes FYI, I'm fixing the blockstore README. This should let you in turn simplify the setup/testing instructions in PRs like https://github.com/edx/frontend-app-library-authoring/pull/4 .

BTW I notice that the `frontend-app-library-authoring` README is similarly in need of some love. I'm not sure if I'll get to it soon, but if you're writing up instructions for your PRs anyways you might as well put them into that README instead :)

**Comment by arbrandes** [comment]
@bradenmacdonald, this is great, thanks!

And yes, the MFE README needs _a lot_ of love.  I'll handle it when I issue my next PR. :+1:

**Comment by natabene** [comment]
@bradenmacdonald Thank you for the contribution. Do you need edX' help with reviewing or merging this?

**Comment by symbolist** [comment]
@natabene I will be able to review this. 🙂

**Comment by bradenmacdonald** [comment]
@symbolist Would you be able to review this this sprint?

**Review by symbolist — APPROVED** [review]
- [x] I tested the instructions for setting up the devstack.
- [x] I ran the integration tests.
- [x] I checked that the production config sample matches what we are using on one of the CI servers.

**Comment by edx-webhook** [comment]
@bradenmacdonald 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/76&entry.1484655318=https://github.com/bradenmacdonald&entry.752974735=2020-08-11+23:14&entry.1917517419=2020-09-14+18:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by edx-webhook** [comment]
@ormsbee, @kdmccormick: thought you might like to know that bradenmacdonald merged this pull request.

**Pull request merged**
