### PR TITLE
FAL-2522 Remove period from python version makefile var

### PR DESCRIPTION
**Pull request by swalladge**
[FAL-2522](https://tasks.opencraft.com/browse/FAL-2522)

Using a period in the docker-compose project name has been observed to cause issues, when using docker-compose 2.0.
For example: https://github.com/edx/blockstore/pull/128#pullrequestreview-774505053
So, normalize all references to 3.8 to 38.
This fixes the issue, and still retains the filenaming linked with the python version used.

**Test instructions**:

- install docker-compose 2.0
- run `make easyserver` and verify it is brought up successfully
- run `make destroy` and verify it is destroyed as expected
- run `make testserver` and verify the testserver is brought up successfully

**Author notes/concerns**:

What's stopping us from removing all these superfluous variables (`PYTHON_VERSION`, `BLOCKSTORE_*`) and renaming the files to their defaults (`Dockerfile`, `docker-compose.yml`)?  The makefile seems very overengineered for what is essentially a convenience wrapper around docker-compose.

### CODE REVIEW

**Comment by natabene** [comment]
@bradenmacdonald Would you like to be the reviewer ?

**Review by bradenmacdonald — APPROVED** [review]
:+1: Thanks for this fix!

I had some issues with the commands until I deleted all my blockstore-related volumes, but then it was working fine.

- [x] I tested this: using `make easyserver` and `make testserver`
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by swalladge** [comment]
@bradenmacdonald thanks, done

**Comment by bradenmacdonald** [comment]
@natabene Whoops, I missed your comment - yes please, I can review this.

**Comment by edx-webhook** [comment]
@swalladge 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/136&entry.1484655318=https://github.com/swalladge&entry.752974735=2021-10-29+06:33&entry.1917517419=2021-11-01+21:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
