### PR TITLE
Upgrade Django to 2.2.17

### PR DESCRIPTION
**Pull request by regisb**
## Description

This is to make sure that we use the same Django version for all applications.

This PR should be merged in time for the Koa release (cc @nedbat); it is ready for review.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-5237](https://openedx.atlassian.net/browse/OSPR-5237) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
For this pull request (and the other 2.2.17 pull requests), did you mean for the base to be master?  It will be simpler to merge directly to open-release/koa.master, and let master get upgraded in the usual ways.

**Comment by regisb** [comment]
@nedbat Well, I figured that if Django had not been upgraded for so long on these repos, then it meant that the upgrade bot was somehow broken. For instance, on this repo (blockstore), Django got upgraded to 2.2.17 a couple hours ago (right after I opened my PR) by https://github.com/edx/blockstore/pull/83.
If you think it makes more sense to open a PR on koa.master instead, I'll close and re-open new PRs.

**Comment by nedbat** [comment]
It's a good point that the upgrade process (whether manual or automatic) seems to be lagging for these repos.  My impulse was to separate the two halves: 1) getting Koa the latest Django, and 2) poking the upgrade process on master, especially where there are conflicts, as here.   For the PRs that merge cleanly, I guess it's good to update master and then cherry-pick.

**Comment by natabene** [comment]
@bradenmacdonald @ormsbee FYI this PR in case you want to review.

**Review by nedbat — APPROVED** [review]

**Comment by nedbat** [comment]
This change is fine, but no longer needed: master is on 2.2.17.

**Comment by edx-webhook** [comment]
@regisb Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/98&entry.1484655318=https://github.com/regisb&entry.752974735=2020-11-23+18:57&entry.1917517419=2020-11-24+21:15&entry.2133058324=No) so we can improve your experience in the future.

**Comment by nedbat** [comment]
But we still need to make the change for Koa.

**Pull request closed without merging**
